trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AzureSP-for-WebApp-Deploy'  # Replace with your service connection name
  appName: 'manish-webapp'                        # Replace with your Azure App Service name
  resourceGroupName: 'your-resource-group-name'   # Replace with actual RG

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Optional: Run tests if you have any
# - script: |
#     pytest
#   displayName: 'Run tests'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    package: '.'
    startupCommand: 'python app.py'  # or 'gunicorn app:app' if using Gunicorn
